name: dagster
services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - path: ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./dagster_home:/opt/dagster/dagster_home
      - ./docker/workspace.yaml:/workspace.yaml
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecom"]
      interval: 10s
      timeout: 8s
      retries: 5

  dagster_codeserver:
    image: dagster-codeserver
    build:
      context: .
      dockerfile: ./docker/Dockerfile_code_location
    container_name: dagster_codeserver
    env_file:
      - path: ./.env
    expose:
      - "4000"
    ports:
      - 4000:4000

  dagster_webserver:
    image: dagster-webserver
    build:
      context: .
      dockerfile: ./docker/Dockerfile_dagster
    container_name: dagster_webserver
    entrypoint: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-w", "workspace.yaml"]
    expose:
      - "3000"
    ports:
      - 3000:3000
    env_file:
      - path: ./.env
    volumes:
      # Make docker client accessible so we can terminate containers from the webserver
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    depends_on:
      postgres:
        condition: service_healthy
      dagster_codeserver:
        condition: service_started

  dagster-daemon:
    image: dagster-daemon
    build:
      context: .
      dockerfile: ./docker/Dockerfile_dagster
    container_name: dagster_daemon
    entrypoint: ["dagster-daemon", "run"]
    env_file:
      - path: ./.env
    volumes:
      # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    depends_on:
      postgres:
        condition: service_healthy
      dagster_codeserver:
        condition: service_started

volumes:
  postgres-db-volume: