[project]
name = "ecom-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dagster>=1.11.3",
    "dagster-dbt>=0.27.3",
    "dagster-webserver>=1.11.3",
    "dbt-core>=1.9.4",
    "dbt-snowflake>=1.9.4",
]
